stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test execution script here

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - pwd
    - mkdir -p nginx
    # Print working directory and list files for debugging
    - pwd
    - ls -la
    - ls -la nginx/
    - docker-compose up -d
