stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."
    - which docker
    - docker compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test execution script here

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - which docker
    - pwd
    - ls -la nginx/
    - docker compose up -d
