services:
  service1:
    build: ./service1
    deploy:
      replicas: 3
    depends_on:
      - service2
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  service2:
    build: ./service2
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8198:8198"
    depends_on:
      - service1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
